version: "3"

services: 
  enrolle-db: 
    container_name: mongo
    image: "mongo:latest"
    ports: 
      - "27017:27017"
  enrollee-app: 
    container_name: enrollee-app
    image: "enrollee-app:1.0"
    links: 
      - enrolle-db
    ports: 
      - "8080:8080"
  
